- name: Install Elasticsearch
  hosts: es_servers
  tasks:
    - name: Install OpenJDK 8
      yum:
        name: java-1.8.0-openjdk-headless
        state: present
    - name: Install Elasticsearch Repository
      yum_repository:
        name: elasticsearch-{{ elasticsearch_branch }}
        description: Elasticsearch repository for {{ elasticsearch_branch }} packages
        baseurl: https://artifacts.elastic.co/packages/{{ elasticsearch_branch }}/yum
        gpgkey: https://packages.elastic.co/GPG-KEY-elasticsearch
        gpgcheck: yes
        enabled: yes
    - name: Install Elasticsearch {{ elasticsearch_branch }}
      yum:
        name: elasticsearch
        state: latest
    - name: Set Elasticsearch Memory Lock
      lineinfile:
        dest: '{{ elasticsearch_config_file }}'
        regexp: '^#bootstrap.memory_lock'
        line: 'bootstrap.memory_lock: true'
    - name: Set Elasticsearch Initial Heap Size
      lineinfile:
        dest: '{{ elasticsearch_jvm_options_file }}'
        regexp: '^-Xms2g'
        line: '-Xms{{ elasticsearch_heap_size }}'
    - name: Set Elasticsearch Maximum Heap Size
      lineinfile:
        dest: '{{ elasticsearch_jvm_options_file }}'
        regexp: '^-Xmx2g'
        line: '-Xmx{{ elasticsearch_heap_size }}'
    - name: Set Elasticsearch Max Locked Memory
      lineinfile:
        dest: '{{ elasticsearch_sysconfig_file }}'
        regexp: '^#MAX_LOCKED_MEMORY'
        line: 'MAX_LOCKED_MEMORY=unlimited'
    - name: Set Elasticsearch Unit file to Enable Memory Lock
      lineinfile:
        dest: '{{ elasticsearch_unit_file }}'
        regexp: '^#LimitMEMLOCK=infinity'
        line: 'LimitMEMLOCK=infinity'
    - name: Set Elasticsearch Node Name
      lineinfile:
        dest: '{{ elasticsearch_config_file }}'
        regexp: '^#node.name:'
        line: 'node.name: ${HOSTNAME}'
    - name: Set Elasticsearch Cluster Name
      lineinfile:
        dest: '{{ elasticsearch_config_file }}'
        regexp: '^#cluster.name:'
        line: 'cluster.name: {{ elasticsearch_cluster_name }}'
    - name: Set Elasticsearch Cluster Members
      lineinfile:
        dest: '{{ elasticsearch_config_file }}'
        regexp: '^#discovery.zen.ping.unicast.hosts'
        line: 'discovery.zen.ping.unicast.hosts: {{ elasticsearch_cluster_nodes }}'
    - name: Set Elasticsearch Minimum Master Nodes
      lineinfile:
        dest: '{{ elasticsearch_config_file }}'
        regexp: '^#discovery.zen.minimum_master_nodes'
        line: 'discovery.zen.minimum_master_nodes: {{ elasticsearch_minimum_masters }}'
    - name: Set Elasticsearch Listening
      lineinfile:
        dest: '{{ elasticsearch_config_file }}'
        regexp: '^#network.host'
        line: 'network.host: ["0.0.0.0"]'
        - name: Set Elasticsearch Max Compression and Disk Allocation Tresholds
      blockinfile:
        dest: '{{ elasticsearch_config_file }}'
        marker: '# {mark} Custom Elasticsearch Parameters'
        block: |
          index.codec: best_compression
          cluster.routing.allocation.disk.threshold_enabled: true
          cluster.routing.allocation.disk.watermark.high: {{ elasticsearch_high_disk_watermark }}
          cluster.routing.allocation.disk.watermark.low: {{ elasticsearch_low_disk_watermark }}
    - name: Start and Enable Elasticsearch Service
      service:
        name: elasticsearch
        enabled: yes
        state: started
