- name: Install Graylog Server
  become_user: root
  hosts: graylog_servers
  vars:
    graylog_version: 2.2
  tasks:
    - name: Install EPEL Repository
      yum:
        name: epel-release
        state: present
    - name: Install OpenJDK 8
      yum:
        name: java-1.8.0-openjdk-headless
        state: present
    - name: Install Password Generator
      yum:
        name: pwgen
        state: present
    - name: Install GNU Coreutils
      yum:
        name: coreutils
        state: present
    - name: Install Graylog Repository
      yum:
        name: https://packages.graylog2.org/repo/packages/graylog-{{ graylog_version }}-repository_latest.rpm
        state: latest
    - name: Install Graylog Server
      yum:
        name: graylog-server
        state: latest
