- name: Install MongoDB Server
  become_user: root
  hosts: graylog_servers
  vars:
    mongodb_version: 3.2
    mongodb_admin_password: open123mongoadmin
    mongodb_graylog_password: open123graylog
  tasks:
    - name: Install MongoDB Repository
      yum_repository:
        name: mongodb-org-3.2
        description: MongoDB Repository
        baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_version }}/x86_64/
        gpgkey: https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc
        gpgcheck: yes
        enabled: yes
    - name: Install MongoDB {{ mongodb_version }}
      yum:
        name: mongodb-org
        state: latest
    - name: Install PIP
      yum:
        name: python-pip
        state: present
    - name: Install Latest PyMongo from PIP
      pip:
        name: pymongo
        state: latest
    - name: Install SELinux tools
      yum:
        name: policycoreutils-python
        state: present
    - name: Adjust MongoDB SELinux Permissions
      seport:
        ports: 27017
        proto: tcp
        setype: mongod_port_t
        state: present
    - name: Start and Enable MongoDB Service
      service:
        name: mongod
        enabled: yes
        state: started
    - name: Wait for MongoDB to start
      pause:
        seconds: 20
    - name: Set MongoDB Admin Password
      mongodb_user:
        login_database: admin
        database: admin
        name: admin
        password: "{{ mongodb_admin_password }}"
        roles: userAdminAnyDatabase
        state: present
    - name: Enable Auth in MongoDB
      blockinfile:
        dest: /etc/mongod.conf
        marker: '# {mark} Auth Section'
        block: |
          security:
            authorization: enabled
    - name: Restart MongoDB to apply changes
      service:
        name: mongod
        state: restarted
    - name: Ceate Graylog DB and Set Password
      mongodb_user:
        database: graylog
        login_database: admin
        login_user: admin
        login_password: "{{ mongodb_admin_password }}"
        name: graylog
        password: "{{ mongodb_graylog_password }}"
        roles: dbOwner
        state: present
