- name: Install Graylog Prereqs
  become_user: root
  hosts: graylog_servers
  tasks:
    - name: Install EPEL Repository
      yum:
        name: epel-release
        state: present
    - name: Install OpenJDK 8
      yum:
        name: java-1.8.0-openjdk-headless
        state: present
    - name: Install SELinux tools
      yum:
        name: policycoreutils-python
        state: present
    - name: Install Password Generator
      yum:
        name: pwgen
        state: present
    - name: Install GNU Coreutils
      yum:
        name: coreutils
        state: present
    - name: Install pymongo
      yum:
        name: python-pymongo
        state: present
